[package]
name = "nfd2nfc-watcher"
version = { workspace = true }
edition = "2021"

[dependencies]
log = { workspace = true }
nfd2nfc-core = { path = "../nfd2nfc-core" }
notify = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
